# Plasma KDE desktop
pacman:
  install:
  - plasma
  - konsole
  - kate
  - dolphin
  - plasma-login-manager
  - packagekit-qt6
systemd:
  default: graphical.target
  enable:
  - plasmalogin.service
+also:
# Ensure NetworkManager is enabled
- packages/network-manager
- packages/firefox
